name: Example action

on: workflow_dispatch

jobs:
  ls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pwd
        id: ls
        run: |
          cd ./ex-site
          ls
