name: Example action

on: push
jobs:
  ls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pwd
        run: |
          cd ./ex-site
          ls
