name: Upload ex-site to Github Pages

on: push

defaults:
  run:
    working-directory: ./ex-site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}

      - name: Building
        run: bun run build

      - name: Upload pages artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
